### ISSUE TITLE
The wiki page is no longer available

### ISSUE THREAD

**Issue by ayoubmoussaid** [ldbc/ldbc_snb_interactive_driver#195]
I can no longer access the wiki page on this link: https://github.com/ldbc/ldbc_driver/wiki
Those docs were helpful for my research!

**Comment by szarnyasg** [comment]
It is slightly outdated, hence I turned it off. I understand it's useful for you, so I turned it back on so you can access it.

**Comment by ayoubmoussaid** [comment]
Thank you very much
