### ISSUE TITLE
Enhancements to update stream conversion script

### ISSUE THREAD

**Issue by szarnyasg** [ldbc/ldbc_snb_interactive_driver#204]
A followup of #203:

* Old `raw` data sets have `hasInterest` instead of `TagId` for the `Person_hasInterest_Tag` table. This is the only difference between the data sets, so re-generating everything is hardly worth it... Rather, the script could/should auto-detect this.
* The batching should be done on a daily basis (opposed to a weekly one), otherwise generating the updates for SF10,000 would require 1.5TiB memory.

**Comment by GLaDAP** [comment]
Would it be feasible to change the column name of the old `raw` datasets possible using something like: 

```
echo "COPY(SELECT creationDate, deletionDate, PersonId, hasInterest as TagId FROM '*.parquet') TO 'Person_hasInterest_Tag.parquet' (FORMAT 'PARQUET')" | duckdb
```

**Comment by szarnyasg** [comment]
They are compressed in `tar.zst` then split in `.tar.zst.000`, so, yes, but at that point I'd rather just regenerate the whole thing on EMR.
