### ISSUE TITLE
create distributed version of driver

### ISSUE THREAD

**Issue by alexaverbuch** [ldbc/ldbc_snb_interactive_driver#7]
multiple driver processes should coordinate (maintain GCT, etc.) to run 1 benchmark in a more scalable manner

details...

**Comment by szarnyasg** [comment]
Commits 3bbbbcb579afc249371e3a74d780075aafa18077 and 967cc67f3fc80e9117802a5f223cee1c96c80064 tell that this will be closed as wontfix.

**Comment by szarnyasg** [comment]
Has a discussion on this with @GLaDAP. This (potentially) depends on https://github.com/ldbc/ldbc_snb_datagen_spark/issues/405

**Comment by szarnyasg** [comment]
Closing this as a wontfix after ~9 years – this will not be implemented in the foreseeable future.
